---
# This workflow will install Python dependencies and run tests

name: Deploy-Dev

on:
  workflow_run:
    workflows: ["Validate-Config"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install CloudFoundry CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | sudo tar -zx --directory=/usr/local/bin
          cf --version

      - name: Setup CF CLI auth and target environment
        run: |
          cf api https://api.fr.cloud.gov
          cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
          cf target -o ${{ secrets.CF_ORG }} -s give-dev

      - name: Ensure DB Available
        run: .cloud-gov/ensure_db_available.sh api-gateway-db

      - name: Deploy application
        run: |
          cf push --vars-file vars.yaml

      - name: Apply CF Network Policies
        run: |
          cf add-network-policy api-gateway ipp-idemia
