---
name: 'Stale-Items'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: >-
            This issue has been automatically marked as stale because it has
            not had any activity in the last 30 days. Remove stale label or
            comment or this will be closed in 5 days.
          stale-pr-message: >-
            This issue has been automatically marked as stale because it has
            not had any activity in the last 30 days. Remove stale label or
            comment or this will be closed in 5 days.
          days-before-stale: 30
          days-before-close: 5
