---
# This workflow will run the OWASP ZAP web application security scanner against
# the IDVA API Gateway

name: Zap-Scan

on:
  workflow_run:
    workflows: ["Deploy"]
    branches: [main]
    types: [completed]

jobs:
  zap_scan:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    name: Scan the API Gateway
    steps:
      - uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: "https://idva-dev.app.cloud.gov"
          rules_file_name: ".zap/rules.tsv"
