---
# This workflow will run the OWASP ZAP web application security scanner against
# the IDVA SK SDK

name: Zap-Scan-SDK

on:
  workflow_run:
    workflows: ["Deploy"]
    branches: [main]
    types: [completed]

jobs:
  zap_scan_api:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    name: Scan the API Gateway - SDK
    steps:
      - uses: actions/checkout@v2

      - name: ZAP Scan (SDK)
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: "https://idva-sdk-dev.app.cloud.gov"
          rules_file_name: ".zap/rules-sdk.tsv"
          issue_title: "ZAP Full Scan Report - SDK"
